-- Fix security issues

-- 1. Drop the security definer view and recreate without it
DROP VIEW IF EXISTS questions_for_play;
CREATE VIEW questions_for_play 
WITH (security_invoker = true)
AS
SELECT 
    qb.id,
    qb.unit_id,
    qb.passage_id,
    qb.game_id,
    qb.word,
    qb.question_text,
    qb.options,
    qb.created_at
FROM question_bank qb;

-- 2. Fix the overly permissive RLS policy - restrict INSERT/UPDATE/DELETE to service role only
-- The service role bypasses RLS anyway, so we need a different approach
-- Let's make the policy more restrictive for non-service-role users
DROP POLICY IF EXISTS "Service role can manage questions" ON question_bank;
DROP POLICY IF EXISTS "Users can insert questions for own generated passages" ON question_bank;

-- Keep the read policy for everyone
-- Add insert policy that requires passage to be generated by user
CREATE POLICY "Users can insert questions for own generated passages" ON question_bank 
  FOR INSERT 
  WITH CHECK (
    passage_id IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM reading_passages
      WHERE reading_passages.id = question_bank.passage_id 
      AND reading_passages.generated_by = auth.uid() 
      AND reading_passages.is_generated = true
    )
  );